/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.util.LinkedList;
import java.util.Vector;

/**
 *
 * @author Vince
 */
public class InterfaceApplication extends javax.swing.JFrame {
    Login Login = new Login(this, true);
    InterfacePeCVeh PeC= new InterfacePeCVeh(this, true);
    InterfaceRdv Rdv = new InterfaceRdv(this, true);
    LinkedList Travail=new LinkedList();
    /**
     * Creates new form InterfaceApplication
     */
    public InterfaceApplication() {
        initComponents();
        Login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelAtelier = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        JTFPont1 = new javax.swing.JTextField();
        JTFPont2 = new javax.swing.JTextField();
        JTFPont3 = new javax.swing.JTextField();
        JTFSol = new javax.swing.JTextField();
        JTFDivers = new javax.swing.JTextField();
        jLabelBureau = new javax.swing.JLabel();
        jLabelBurCompta = new javax.swing.JLabel();
        jLabelBuCli = new javax.swing.JLabel();
        jLabelCom = new javax.swing.JLabel();
        JTFBuCli = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAPrevoir = new javax.swing.JMenuItem();
        jMenuPEC = new javax.swing.JMenu();
        jMenuTerminé = new javax.swing.JMenuItem();
        jMenuListes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pont n 1:");

        jLabel2.setText("Pont n 2:");

        jLabel3.setText("Pont n 3:");

        jLabel4.setText("Sol:");

        jLabel5.setText("Divers:");

        jLabelAtelier.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelAtelier.setText("Atelier");

        jLabelDate.setText("Date/heure");

        JTFPont1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFPont1ActionPerformed(evt);
            }
        });

        JTFPont3.setToolTipText("");

        jLabelBureau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelBureau.setText("Bureau");

        jLabelBurCompta.setText("Bureau comptabilité:");

        jLabelBuCli.setText("Bureau client:");

        jLabelCom.setText("Com");

        jMenu1.setText("Atelier");

        jMenuAPrevoir.setText("A prévoir");
        jMenuAPrevoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAPrevoirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAPrevoir);

        jMenuPEC.setText("Prise en charge");
        jMenuPEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPECActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPEC);

        jMenuTerminé.setText("Terminé");
        jMenuTerminé.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTerminéActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuTerminé);

        jMenuListes.setText("Listes");
        jMenu1.add(jMenuListes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Matériel");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Clients");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Factures");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("                                                                                                                                                                      ");
        jMenu5.setContentAreaFilled(false);
        jMenu5.setEnabled(false);
        jMenu5.setFocusable(false);
        jMenu5.setRequestFocusEnabled(false);
        jMenu5.setRolloverEnabled(false);
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Paramètres");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Aide");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelAtelier, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jLabelBureau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBurCompta)
                            .addComponent(jLabelBuCli))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTFPont2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(JTFPont3)
                            .addComponent(JTFSol)
                            .addComponent(JTFPont1)
                            .addComponent(JTFDivers)
                            .addComponent(JTFBuCli)
                            .addComponent(jLabelCom))))
                .addGap(168, 386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelAtelier))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDate)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTFPont1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFPont2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFPont3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFSol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFDivers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(jLabelBureau)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuCli)
                    .addComponent(JTFBuCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBurCompta)
                    .addComponent(jLabelCom))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFPont1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFPont1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFPont1ActionPerformed

    private void jMenuAPrevoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAPrevoirActionPerformed
        // TODO add your handling code here:
        Rdv.setVisible(true);
    }//GEN-LAST:event_jMenuAPrevoirActionPerformed

    private void jMenuTerminéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTerminéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuTerminéActionPerformed

    private void jMenuPECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPECActionPerformed
        PeC.setVisible(true);
    }//GEN-LAST:event_jMenuPECActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFBuCli;
    private javax.swing.JTextField JTFDivers;
    private javax.swing.JTextField JTFPont1;
    private javax.swing.JTextField JTFPont2;
    private javax.swing.JTextField JTFPont3;
    private javax.swing.JTextField JTFSol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAtelier;
    private javax.swing.JLabel jLabelBuCli;
    private javax.swing.JLabel jLabelBurCompta;
    private javax.swing.JLabel jLabelBureau;
    private javax.swing.JLabel jLabelCom;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuAPrevoir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuListes;
    private javax.swing.JMenu jMenuPEC;
    private javax.swing.JMenuItem jMenuTerminé;
    // End of variables declaration//GEN-END:variables
}
